FROM node:12.3.1
{{#each sharedDirectories}}

WORKDIR /{{this}}
COPY {{this}}/package-lock.json package-lock.json
COPY {{this}}/package.json package.json
RUN npm install
COPY {{this}}/src src

{{/each}}
WORKDIR /app
COPY {{serviceName}}/yarn.lock yarn.lock
COPY {{serviceName}}/package.json package.json
RUN yarn
COPY {{serviceName}}/src /app/src
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "prod"]
